name: Build LaTeX document
on: [ push ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
        
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: resume.pdf
          
      - name: Setup PDF commit
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.pdf
          git commit -m "Update PDF via bot"
                
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
